spring.application.name=zion-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_empresarial
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
