spring.application.name=zion

spring.datasource.url=jdbc:postgresql://ep-solitary-surf-am5b00y2-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UV6K8fdMQgXv
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

server.port=8080

# JWT Config
jwt.secret=ZionSuperSecretKey2026AbcDef123456789!#ProjectJWT_MustBe32CharsOrMore
jwt.expiration=28800000

#spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_empresarial
#spring.datasource.username=postgres
#spring.datasource.password=1234